# fly.co1.toml for Pressmatics WhatsApp Microservice (Company 1)

app = "pressmatics-whatsapp"
primary_region = "sin"

[build]

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
